#當前web應用端口 默認8080
server:
  port: 8080

spring:
  application:
    name: helloWorld

#連接資料庫
  datasource:
    url: jdbc:mysql://localhost:3306/pet_db?useSSL=false&serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: root
    password: 881227
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    #生成的sql語句顯示在控制台
    show-sql: true
    # 格式化(美化)
    properties:
      hibernate:
        format_sql: true
    #自動更新資料庫表結構
    hibernate:  #ORM框架 (物件關聯對應)
      ddl-auto: update
